/**
 * @file    cnn_inference.c
 * @brief   MAX78000 Hardware CNN Accelerator Implementation for TBS Grading.
 * @project Edge AI Palm Oil FFB (TBS) Grading System
 *
 * @details Implements the full CNN inference pipeline: hardware initialization,
 *          input loading, accelerator execution, and result extraction with
 *          argmax and confidence calculation.
 *
 * @generated_code_dependency
 *   This module wraps the auto-generated code from ai8x-synthesis:
 *     - cnn_generated/tbs_cnn.c   → Defines: cnn_enable(), cnn_load_weights(),
 *                                             cnn_configure(), cnn_start(), etc.
 *     - cnn_generated/tbs_cnn.h   → Declares the above functions
 *     - cnn_generated/weights.h   → Compiled weight arrays (read-only flash)
 */

#include "../include/cnn_inference.h"

/* MSDK system includes */
#include "mxc_device.h"
#include "mxc_sys.h"
#include "mxc_delay.h"
#include "nvic_table.h"      /* NVIC interrupt configuration */

/* Generated code from ai8x-synthesis (placed in cnn_generated/) */
#include "../cnn_generated/tbs_cnn.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* ── Private Constants ────────────────────────────────────────────────────── */

/**
 * @brief  MAX78000 CNN clock source.
 *         MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK = peripheral clock.
 *         Some MSDK versions use MXC_CNN_CLKSEL values — check mxc_sys.h.
 */
#define CNN_CLOCK_SOURCE    MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK

/**
 * @brief  CNN clock divider.
 *         Divider of 1 = maximum speed (full PCLK rate, typically 100 MHz).
 */
#define CNN_CLOCK_DIV       MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1

/**
 * @brief  Size of the CNN output buffer.
 *         CNN_NUM_CLASSES INT32 values (one logit per class).
 */
#define CNN_OUTPUT_SIZE     (CNN_NUM_CLASSES)

/* ── Grade Name String Table (ROM-resident) ───────────────────────────────── */

/** Human-readable class name array. Index must match CLASS_* constants. */
static const char * const s_class_names[CNN_NUM_CLASSES] = {
    "Mentah",           /* Class 0: Unripe */
    "Matang",           /* Class 1: Ripe (optimal) */
    "Overripe",         /* Class 2: Over-ripe */
    "Janjang Kosong"    /* Class 3: Empty bunch */
};

/* ── Private State ────────────────────────────────────────────────────────── */

/** Tracks whether cnn_hw_init() completed successfully */
static bool s_cnn_initialized = false;

/**
 * @brief  Global input pointer used by the generated cnn_load_input() stub.
 *         The generated cnn_load_input() reads pixel data from this pointer.
 *         Set in preprocess.c before calling preprocess_load_into_cnn_sram().
 */
const int8_t *g_cnn_input_ptr = NULL;

/**
 * @brief  Output logit buffer — populated by cnn_unload() after inference.
 *         INT32 because the CNN accumulator produces 32-bit values.
 */
static uint32_t s_cnn_output_raw[CNN_OUTPUT_SIZE];

/* ── Public API Implementation ────────────────────────────────────────────── */

cnn_status_t cnn_hw_init(void)
{
    int ret;

    printf("[CNN] Initializing MAX78000 CNN hardware accelerator...\r\n");

    /*
     * Step 1: Enable CNN peripheral clock and power up CNN SRAM banks.
     *
     * cnn_enable() is generated by ai8x-synthesis. It:
     *   a) Gates the CNN peripheral clock on (via MXC_GCR->pclkdiv register)
     *   b) Powers up all CNN data SRAM banks (64 banks × 4 instances)
     *   c) Resets the CNN state machine to a known idle state
     *
     * Parameters: clock source and divider define the CNN operating frequency.
     * Running at maximum speed minimizes inference latency.
     */
    ret = cnn_enable(CNN_CLOCK_SOURCE, CNN_CLOCK_DIV);
    if (ret != CNN_OK) {
        printf("[CNN] ERROR: cnn_enable() failed: %d\r\n", ret);
        return CNN_ERR_INIT;
    }

    /*
     * Step 2: Load pre-trained weights from flash into CNN weight SRAM.
     *
     * cnn_load_weights() is generated by ai8x-synthesis. It reads the
     * weight arrays from weights.h (compiled into flash) and writes them
     * into the CNN's dedicated weight memory banks.
     *
     * This is a one-time operation — weights remain in CNN SRAM until
     * cnn_disable() is called (which powers down the CNN SRAM).
     * If CNN is kept enabled between inferences, this only needs to run once.
     */
    ret = cnn_load_weights();
    if (ret != CNN_OK) {
        printf("[CNN] ERROR: cnn_load_weights() failed: %d\r\n", ret);
        return CNN_ERR_LOAD;
    }

    /*
     * Step 3: Load bias values (typically zero for our model since we
     * disabled biases in Conv layers to save weight memory).
     * cnn_load_bias() is a no-op if no bias was compiled in.
     */
    ret = cnn_load_bias();
    if (ret != CNN_OK) {
        printf("[CNN] WARNING: cnn_load_bias() failed (non-fatal): %d\r\n", ret);
        /* Non-fatal — continue initialization */
    }

    /*
     * Step 4: Configure CNN topology (layer parameters, data flow).
     *
     * cnn_configure() programs the CNN's layer configuration registers
     * with the topology defined at synthesis time. This includes:
     *   - Number of layers
     *   - Kernel sizes per layer
     *   - Pooling parameters
     *   - Data memory routing between layers
     */
    ret = cnn_configure();
    if (ret != CNN_OK) {
        printf("[CNN] ERROR: cnn_configure() failed: %d\r\n", ret);
        return CNN_ERR_INIT;
    }

    /* Clear output buffer */
    memset(s_cnn_output_raw, 0, sizeof(s_cnn_output_raw));

    s_cnn_initialized = true;

    printf("[CNN] CNN accelerator initialized. Weights loaded. Ready.\r\n");
    return CNN_OK;
}

cnn_status_t cnn_load_input(const int8_t *input_data)
{
    if (input_data == NULL) {
        printf("[CNN] ERROR: input_data is NULL.\r\n");
        return CNN_ERR_NULL_PTR;
    }

    if (!s_cnn_initialized) {
        printf("[CNN] ERROR: cnn_hw_init() not called.\r\n");
        return CNN_ERR_INIT;
    }

    /* Update the global pointer used by the generated cnn_load_input stub */
    g_cnn_input_ptr = input_data;

    /*
     * Call the generated cnn_load_input() from tbs_cnn.c.
     * This function reads from g_cnn_input_ptr and writes the INT8
     * pixel data into the CNN's input data SRAM in the mexpress-optimized
     * format that the HW accelerator expects.
     *
     * The generated loader packs 4 INT8 values per 32-bit word write,
     * maximizing memory bus efficiency.
     *
     * Note: In the generated tbs_cnn.c, the function may be named differently.
     * Common names: cnn_load_input(), load_input(). Check tbs_cnn.h.
     */
    /* This is defined in cnn_generated/tbs_cnn.c and loads from g_cnn_input_ptr */
    /* Calling the generated MSDK CNN function: */
    extern void cnn_input_load(void);  /* Actual name may vary — check tbs_cnn.h */
    cnn_input_load();

    return CNN_OK;
}

cnn_status_t cnn_start_and_wait(void)
{
    if (!s_cnn_initialized) {
        printf("[CNN] ERROR: cnn_hw_init() not called.\r\n");
        return CNN_ERR_INIT;
    }

    /*
     * Start the CNN accelerator.
     *
     * cnn_start() writes to the CNN START control register, which triggers
     * the hardware state machine to begin executing the configured topology
     * with the data currently in CNN SRAM.
     *
     * The accelerator operates autonomously — the CPU core is free immediately
     * after cnn_start() returns. CNN completion is signaled via:
     *   a) Polling the CNN DONE status bit
     *   b) CNN completion interrupt (CNN_IRQ)
     *
     * We use __WFI()-based polling here for a balance of simplicity and
     * power efficiency (core sleeps while CNN runs).
     */
    cnn_start();

    /*
     * Wait for CNN inference to complete.
     *
     * Poll-with-sleep strategy:
     *   - Use __WFI() to enter core sleep between polls
     *   - CNN completion interrupt (if enabled) will wake the core
     *   - Fall back to timeout if interrupt is not configured
     *
     * Typical inference time for TBSClassifier on MAX78000 at 100 MHz: ~3-8 ms
     */
    uint32_t timeout_counter = 0;
    const uint32_t max_polls = CNN_TIMEOUT_MS * 10;  /* ~100µs per poll */

    while (!MXC_CNN_CheckComplete()) {
        /* Sleep core until next interrupt (CNN done, SysTick, etc.) */
        __WFI();

        timeout_counter++;
        if (timeout_counter >= max_polls) {
            printf("[CNN] ERROR: Inference timeout after %u ms.\r\n", CNN_TIMEOUT_MS);
            return CNN_ERR_TIMEOUT;
        }
    }

    return CNN_OK;
}

cnn_status_t cnn_get_result(cnn_result_t *result)
{
    if (result == NULL) {
        printf("[CNN] ERROR: result is NULL.\r\n");
        return CNN_ERR_NULL_PTR;
    }

    /*
     * Unload CNN output logits from CNN output SRAM.
     *
     * cnn_unload() reads the final layer output values from the CNN output
     * data SRAM into the provided buffer. Values are INT32 (wide accumulator).
     * Each value represents the raw logit for one class.
     *
     * Higher logit → higher model confidence in that class.
     * Logit values are NOT probabilities (apply softmax for probabilities).
     */
    cnn_unload(s_cnn_output_raw);

    /*
     * Copy raw logits into result struct.
     * The raw values are stored as uint32_t by the generated API for
     * memory alignment reasons, but the actual values are INT32 signed.
     * Cast appropriately.
     */
    for (uint8_t i = 0; i < CNN_NUM_CLASSES; i++) {
        result->raw_logits[i] = (int32_t)s_cnn_output_raw[i];
    }

    /*
     * ── Argmax: Find the winning class ────────────────────────────────────
     * Linear scan to find the index of the maximum logit value.
     * The class with the highest logit is the model's prediction.
     */
    int32_t  max_logit = result->raw_logits[0];
    uint8_t  max_idx   = 0;

    for (uint8_t i = 1; i < CNN_NUM_CLASSES; i++) {
        if (result->raw_logits[i] > max_logit) {
            max_logit = result->raw_logits[i];
            max_idx   = i;
        }
    }
    result->grade = max_idx;

    /*
     * ── Confidence Estimation (Softmax Approximation) ────────────────────
     *
     * True softmax requires exp() which is expensive on a Cortex-M4.
     * We use a fast linear approximation:
     *
     *   softmax_approx[i] = ReLU(logit[i]) / sum_j(ReLU(logit[j]))
     *
     * This approximation works because:
     *   1. ReLU zeros out negative logits (which the model is "against")
     *   2. The winner always has the highest positive contribution
     *   3. The resulting ratio is a reasonable proxy for confidence
     *
     * If ALL logits are negative (degenerate case — model is uncertain
     * about all classes), we report 0% confidence as a safety flag.
     *
     * Scale to [0, 100]% for compact JSON transmission.
     */
    int64_t sum_relu = 0;  /* Use int64 to prevent overflow for large logits */

    for (uint8_t i = 0; i < CNN_NUM_CLASSES; i++) {
        int32_t relu_val = (result->raw_logits[i] > 0) ? result->raw_logits[i] : 0;
        sum_relu += (int64_t)relu_val;
    }

    if (sum_relu == 0) {
        /* Degenerate: all logits ≤ 0 — model is maximally uncertain */
        result->confidence_pct = 0;
        printf("[CNN] WARNING: All output logits are non-positive. Low confidence.\r\n");
    } else {
        int32_t winner_relu = (result->raw_logits[max_idx] > 0)
                              ? result->raw_logits[max_idx]
                              : 0;

        /* Compute percentage: (winner_relu / sum_relu) * 100 */
        /* Use integer arithmetic with scaling to avoid floating point */
        result->confidence_pct = (uint8_t)((winner_relu * 100LL) / sum_relu);
    }

    /* Log result */
    printf("[CNN] Result: Grade=%u (%s), Confidence=%u%%\r\n",
           result->grade,
           cnn_get_class_name(result->grade),
           result->confidence_pct);

    printf("[CNN] Raw logits: [%ld, %ld, %ld, %ld]\r\n",
           (long)result->raw_logits[0], (long)result->raw_logits[1],
           (long)result->raw_logits[2], (long)result->raw_logits[3]);

    return CNN_OK;
}

const char *cnn_get_class_name(uint8_t grade_index)
{
    if (grade_index >= CNN_NUM_CLASSES) {
        return "UNKNOWN";
    }
    return s_class_names[grade_index];
}

cnn_status_t cnn_hw_disable(void)
{
    /*
     * Power down the CNN accelerator to save energy.
     *
     * cnn_disable() (generated by ai8x-synthesis):
     *   1. Gates the CNN peripheral clock off
     *   2. Powers down CNN data SRAM banks
     *
     * WARNING: After cnn_disable(), all weights in CNN SRAM are lost.
     *          Call cnn_hw_init() again before the next inference.
     *
     * Power consumption comparison:
     *   CNN active (idle between inferences): ~5-10 mW
     *   CNN disabled (clock gated):           ~0.1 mW
     *
     * Recommendation: Disable CNN only if the next inference is >10 seconds
     *                 away. Otherwise, keep CNN enabled to avoid the
     *                 ~1ms weight reload latency.
     */
    int ret = cnn_disable();
    if (ret != CNN_OK) {
        printf("[CNN] WARNING: cnn_disable() returned error: %d\r\n", ret);
        /* Non-fatal — hardware may already be in disabled state */
    }

    s_cnn_initialized = false;
    printf("[CNN] CNN accelerator disabled (clock gated, SRAM powered down).\r\n");

    return CNN_OK;
}
