/**
 * @file    cnn_inference.h
 * @brief   MAX78000 Hardware CNN Accelerator Interface for TBS Grading.
 * @project Edge AI Palm Oil FFB (TBS) Grading System
 *
 * @details Provides a high-level abstraction over the MAX78000 CNN hardware
 *          accelerator (CNNA) primitives. Wraps the low-level generated
 *          code from ai8x-synthesis (tbs_cnn.c / tbs_cnn.h) into a clean,
 *          application-friendly API.
 *
 * @hardware_accelerator
 *   The MAX78000 CNNA is a dedicated fixed-function neural network processor:
 *   - 64 parallel processing elements (PEs)
 *   - Dedicated on-chip weight memory (442 KB)
 *   - Dedicated on-chip data SRAM (CNN SRAM, separate from system SRAM)
 *   - INT8 multiply-accumulate with 32-bit accumulators
 *   - Hardware pooling and activation functions
 *
 * @inference_flow
 *   cnn_hw_init() → cnn_load_input(buffer) → cnn_start_and_wait() → cnn_get_result()
 *
 * @class_mapping
 *   Index 0 → Busuk        (Rotten)
 *   Index 1 → Jangkos      (Empty Bunch / Janjang Kosong)
 *   Index 2 → Matang       (Ripe / Optimal)
 *   Index 3 → Mentah       (Unripe)
 */

#ifndef CNN_INFERENCE_H
#define CNN_INFERENCE_H

#include <stdint.h>

/* ── Public Constants ─────────────────────────────────────────────────────── */

/** Number of output classes from the CNN */
#define CNN_NUM_CLASSES     (4U)

/**
 * @brief CNN inference timeout in milliseconds.
 *        Empirical value for 128x128 TBSClassifier on MAX78000.
 *        Typical inference time: ~2-5 ms at 100 MHz CNN clock.
 */
#define CNN_TIMEOUT_MS      (50U)

/** Grade class name lookup table index values (must match ai8x-synthesis output order) */
#define CNN_CLASS_BUSUK             (0U)  /**< Rotten */
#define CNN_CLASS_JANGKOS           (1U)  /**< Empty bunch (Janjang Kosong) */
#define CNN_CLASS_MATANG            (2U)  /**< Ripe (optimal) */
#define CNN_CLASS_MENTAH            (3U)  /**< Unripe */

/* ── Data Types ───────────────────────────────────────────────────────────── */

/**
 * @brief Structure holding the result of one CNN inference pass.
 *
 * @field grade         Predicted class index [0..CNN_NUM_CLASSES-1].
 * @field confidence_pct Softmax-approximated confidence [0..100] percent.
 * @field raw_logits    Raw INT32 output logits from hardware (all classes).
 *                      Useful for logging, thresholding, or ensemble methods.
 */
typedef struct {
    uint8_t  grade;                          /**< Predicted class index */
    uint8_t  confidence_pct;                 /**< Confidence percentage [0,100] */
    int32_t  raw_logits[CNN_NUM_CLASSES];    /**< Raw CNN output values */
} cnn_result_t;

/**
 * @brief CNN module status/error codes.
 */
typedef enum {
    CNN_OK              =  0,  /**< Success */
    CNN_ERR_INIT        = -1,  /**< Hardware init failed */
    CNN_ERR_TIMEOUT     = -2,  /**< Inference timed out */
    CNN_ERR_LOAD        = -3,  /**< Weight loading failed */
    CNN_ERR_NULL_PTR    = -4,  /**< Null pointer argument */
} cnn_status_t;

/* ── Public API ───────────────────────────────────────────────────────────── */

/**
 * @brief  Initialize the MAX78000 CNN hardware accelerator.
 *
 * @details Performs the following sequence:
 *   1. Enables clock to the CNN peripheral (via MXC_GCR registers).
 *   2. Powers up all CNN data SRAM banks.
 *   3. Calls cnn_load_weights() — copies weights from cnn_generated/weights.h
 *      into the CNN's dedicated weight memory.
 *   4. Calls cnn_load_bias() — loads any bias values (typically zero).
 *   5. Calls cnn_configure() — sets layer topology parameters.
 *
 * @note   Call once at system startup. Weights remain loaded in CNN SRAM
 *         and do not need to be reloaded between inferences.
 * @note   CNN SRAM is separate from system SRAM — it is NOT zeroed by default
 *         on reset. Always call cnn_hw_init() before first inference.
 *
 * @return CNN_OK on success, CNN_ERR_INIT on hardware initialization failure.
 */
cnn_status_t cnn_hw_init(void);

/**
 * @brief  Load preprocessed INT8 image data into CNN input SRAM.
 *
 * @details Writes the 128x128x3 HWC INT8 tensor into the CNN accelerator's
 *          input data memory region. Uses the optimized memory write path
 *          generated by ai8x-synthesis (mexpress format).
 *
 * @param[in] input_data  Pointer to preprocessed INT8 HWC tensor.
 *                        Size must be 128*128*3 = 49,152 bytes.
 *
 * @return CNN_OK on success, CNN_ERR_NULL_PTR if input_data is NULL.
 */
cnn_status_t cnn_load_input(const int8_t *input_data);

/**
 * @brief  Start CNN hardware execution and wait for completion.
 *
 * @details Triggers the CNN accelerator via the START bit in the CNN
 *          control register, then polls the DONE bit until inference
 *          completes or timeout occurs.
 *
 *          For power efficiency, the implementation uses __WFI() (Wait For
 *          Interrupt) within the polling loop — CNN completion can trigger
 *          an interrupt to wake the core.
 *
 * @return CNN_OK if inference completed successfully.
 *         CNN_ERR_TIMEOUT if CNN did not complete within CNN_TIMEOUT_MS.
 */
cnn_status_t cnn_start_and_wait(void);

/**
 * @brief  Read output logits and compute grade + confidence.
 *
 * @details Reads the 4 INT32 output logits from the CNN output SRAM region
 *          using cnn_unload(). Then applies argmax to find the winning class
 *          and a softmax approximation to compute confidence percentage.
 *
 *          Softmax approximation used (avoids exp() on embedded target):
 *            softmax_approx[i] = relu(logit[i]) / sum(relu(logit[j]))
 *          Falls back to argmax-only (confidence=0) if all logits are ≤ 0.
 *
 * @param[out] result  Pointer to cnn_result_t struct to populate.
 *
 * @return CNN_OK on success, CNN_ERR_NULL_PTR if result is NULL.
 */
cnn_status_t cnn_get_result(cnn_result_t *result);

/**
 * @brief  Get human-readable class name string for a grade index.
 *
 * @param  grade_index  Class index [0..CNN_NUM_CLASSES-1].
 * @return Constant string pointer (ROM-resident, do not free).
 *         Returns "UNKNOWN" for invalid indices.
 */
const char *cnn_get_class_name(uint8_t grade_index);

/**
 * @brief  Disable the CNN accelerator to save power between inferences.
 *
 * @details Powers down CNN SRAM banks and gates the CNN clock.
 *          Weights are lost and must be reloaded with cnn_hw_init() before
 *          the next inference — OR keep CNN enabled between inferences
 *          (consumes ~5 mW vs ~0 mW when gated) for faster response time.
 *
 * @note   Call this only if the system will be in deep sleep for extended
 *         periods. For frequent scanning (< 5 second intervals), keep CNN on.
 *
 * @return CNN_OK on success.
 */
cnn_status_t cnn_hw_disable(void);

#endif /* CNN_INFERENCE_H */
