/**
 * @file    preprocess.h
 * @brief   Image Preprocessing Pipeline Interface for TBS CNN Input.
 * @project Edge AI Palm Oil FFB (TBS) Grading System
 *
 * @details Provides preprocessing functions to transform raw RGB565 camera
 *          pixel data into the INT8 input format expected by the MAX78000
 *          hardware CNN accelerator, as generated by ai8x-synthesis.
 *
 * @input_format
 *   Raw camera buffer: uint8_t array, RGB565 packed (2 bytes per pixel)
 *   Buffer layout: [R5G6B5_pixel0_MSB, R5G6B5_pixel0_LSB, ...]
 *
 * @output_format
 *   CNN input tensor: int8_t array in HWC (Height-Width-Channel) layout
 *   HWC layout: [R_px0, G_px0, B_px0, R_px1, G_px1, B_px1, ...]
 *   Value range: [-128, 127] (INT8 signed)
 *   Normalization: value = (uint8_channel - 128)
 *                  Maps [0,255] uint8 → [-128,127] int8
 *
 * @buffer_size
 *   CNN input buffer: 128 * 128 * 3 channels * 1 byte = 49,152 bytes (~48 KB)
 *
 * @convention
 *   All functions return 0 on success, negative value on error.
 */

#ifndef PREPROCESS_H
#define PREPROCESS_H

#include <stdint.h>

/* ── Public Constants ─────────────────────────────────────────────────────── */

/** Width of the CNN input tensor in pixels */
#define PREPROCESS_IMG_WIDTH    (128U)

/** Height of the CNN input tensor in pixels */
#define PREPROCESS_IMG_HEIGHT   (128U)

/** Number of color channels (RGB) */
#define PREPROCESS_IMG_CHANNELS (3U)

/**
 * @brief  Total CNN input buffer size in bytes (HWC format).
 *         128 * 128 * 3 = 49,152 bytes.
 */
#define PREPROCESS_CNN_INPUT_SIZE \
    (PREPROCESS_IMG_WIDTH * PREPROCESS_IMG_HEIGHT * PREPROCESS_IMG_CHANNELS)

/* ── Preprocessing Error Codes ───────────────────────────────────────────── */

typedef enum {
    PREPROCESS_OK           =  0,  /**< Success */
    PREPROCESS_ERR_NULL_PTR = -1,  /**< Null pointer argument */
    PREPROCESS_ERR_RANGE    = -2,  /**< Value out of expected range */
} preprocess_status_t;

/* ── Public API ───────────────────────────────────────────────────────────── */

/**
 * @brief  Convert raw RGB565 camera buffer to signed INT8 CNN input tensor.
 *
 * @details Performs a two-step pixel transformation:
 *   Step 1 — Unpack RGB565 to 8-bit channels:
 *     R8 = (pixel[15:11] << 3)  — 5-bit R expanded to 8-bit
 *     G8 = (pixel[10:5]  << 2)  — 6-bit G expanded to 8-bit
 *     B8 = (pixel[4:0]   << 3)  — 5-bit B expanded to 8-bit
 *
 *   Step 2 — Normalize to INT8 signed:
 *     int8_val = (int8_t)(uint8_channel - 128)
 *     Maps [0,255] → [-128,127]
 *
 *   Output is stored in HWC (Height-Width-Channel) interleaved format
 *   as required by the ai8x-synthesis generated cnn_load_input() function.
 *
 * @param[in]  raw_rgb565   Pointer to raw camera frame buffer (RGB565 packed).
 *                          Size: CAMERA_FRAME_BUFFER_SIZE bytes.
 * @param[out] cnn_input    Pointer to output INT8 tensor buffer (HWC layout).
 *                          Size: PREPROCESS_CNN_INPUT_SIZE bytes.
 *                          Caller must allocate this buffer.
 *
 * @return PREPROCESS_OK on success, error code on failure.
 */
preprocess_status_t preprocess_normalize_to_int8(
    const uint8_t *raw_rgb565,
    int8_t        *cnn_input
);

/**
 * @brief  Apply local contrast enhancement to the CNN input tensor (in-place).
 *
 * @details Implements a simplified local contrast normalization (LCN) stub
 *          to compensate for variations in the industrial LED ring light
 *          intensity across the conveyor belt scan area.
 *
 *          Algorithm (per channel, per spatial location):
 *            local_mean = average of a 5x5 neighborhood
 *            enhanced   = clamp(original - local_mean, -128, 127)
 *
 *          In practice on the MAX78000, a full per-pixel 5x5 mean is
 *          computationally expensive. This implementation uses a
 *          single-pass global channel mean subtraction as a fast approximation
 *          that handles global DC offset (uniform over/under-exposure).
 *
 * @note   This function modifies the buffer in-place. Call AFTER
 *         preprocess_normalize_to_int8().
 *
 * @param[in,out] cnn_input  INT8 HWC tensor buffer to enhance in place.
 *                           Size: PREPROCESS_CNN_INPUT_SIZE bytes.
 *
 * @return PREPROCESS_OK on success.
 */
preprocess_status_t preprocess_contrast_enhance(int8_t *cnn_input);

/**
 * @brief  Copy the preprocessed INT8 buffer into CNN accelerator data SRAM.
 *
 * @details Writes the 49,152-byte HWC tensor into the CNN hardware's
 *          dedicated input data memory at the base address expected by
 *          the generated cnn_load_input() stub.
 *          This function provides a direct memory copy path as an
 *          alternative to the ai8x-synthesis-generated loader if
 *          custom DMA loading is desired.
 *
 * @param[in] cnn_input  Pointer to preprocessed INT8 HWC tensor.
 *                       Size: PREPROCESS_CNN_INPUT_SIZE bytes.
 *
 * @return PREPROCESS_OK on success, PREPROCESS_ERR_NULL_PTR on null input.
 */
preprocess_status_t preprocess_load_into_cnn_sram(const int8_t *cnn_input);

#endif /* PREPROCESS_H */
