/**
 * @file    tbs_cnn.c
 * @brief   STUB: ai8x-synthesis Generated CNN Implementation Placeholder.
 * @project Edge AI Palm Oil FFB (TBS) Grading System
 *
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║  IMPORTANT: THIS FILE IS A PLACEHOLDER/STUB                        ║
 * ║                                                                      ║
 * ║  Replace this file with the actual tbs_cnn.c generated by:         ║
 * ║    python ai8xize.py --prefix tbs_cnn ...                           ║
 * ║                                                                      ║
 * ║  The real generated file will contain:                              ║
 * ║    - cnn_enable(): Clock/power enable sequence                      ║
 * ║    - cnn_load_weights(): Weight transfer from weights.h to CNN SRAM ║
 * ║    - cnn_configure(): Layer topology register programming           ║
 * ║    - cnn_input_load(): Mexpress-optimized input tensor loader       ║
 * ║    - cnn_start(): CNN start trigger                                 ║
 * ║    - cnn_unload(): Output logit extraction                          ║
 * ║    - cnn_disable(): Clock gate and power down                       ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 *
 * @note   The stub implementations below allow the project to compile
 *         for simulation/testing purposes. They do NOT execute on real
 *         hardware — replace with the real ai8xize output before flashing.
 */

#include "tbs_cnn.h"
#include "../include/cnn_inference.h"  /* For CNN_NUM_CLASSES */

#include <stdio.h>
#include <string.h>
#include <stdint.h>

/* ── Global: Input data pointer ───────────────────────────────────────────── */
/* Set by preprocess.c before calling cnn_input_load() */
const int8_t *g_cnn_input_ptr = NULL;

/* ── Stub Implementations ─────────────────────────────────────────────────── */

int cnn_enable(uint32_t clock_source, uint32_t clock_div)
{
    (void)clock_source;
    (void)clock_div;
    printf("[CNN_STUB] cnn_enable() called. STUB — replace with generated code.\r\n");
    /*
     * REAL IMPLEMENTATION (generated by ai8xize.py):
     *   MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV
     *                        | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
     *                       | MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1
     *                       | MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK;
     *   MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN);
     *   // Power up all 4x16 CNN SRAM banks
     *   MXC_PWRSEQ->lpcn &= ~(MXC_F_PWRSEQ_LPCN_RAMRET0 | ...);
     */
    return 0;  /* CNN_OK */
}

int cnn_load_weights(void)
{
    printf("[CNN_STUB] cnn_load_weights() called. STUB — weights.h is empty.\r\n");
    /*
     * REAL IMPLEMENTATION:
     *   Iterates through the weight arrays defined in weights.h
     *   and writes them to CNN weight SRAM via volatile uint32_t pointers
     *   at addresses 0x50400000 + layer_offsets.
     *
     *   Example structure (generated for each layer):
     *     static const uint32_t kernels[] = { ... };  // from weights.h
     *     memcpy_io((volatile uint32_t *)CNN_WEIGHT_BASE, kernels, sizeof(kernels));
     */
    return 0;
}

int cnn_load_bias(void)
{
    printf("[CNN_STUB] cnn_load_bias() called. No bias — stub is a no-op.\r\n");
    /* Our model has bias=False in Conv layers — this is a true no-op */
    return 0;
}

int cnn_configure(void)
{
    printf("[CNN_STUB] cnn_configure() called. STUB — layer regs not programmed.\r\n");
    /*
     * REAL IMPLEMENTATION:
     *   Programs CNN control registers for each layer (kernel size, padding,
     *   pooling, activation, memory routing). Hundreds of register writes.
     *   All generated from the YAML network config by ai8xize.py.
     */
    return 0;
}

void cnn_input_load(void)
{
    if (g_cnn_input_ptr == NULL) {
        printf("[CNN_STUB] cnn_input_load(): g_cnn_input_ptr is NULL!\r\n");
        return;
    }
    printf("[CNN_STUB] cnn_input_load() called. Would load %u bytes to CNN SRAM.\r\n",
           (unsigned int)(128 * 128 * 3));
    /*
     * REAL IMPLEMENTATION (mexpress format):
     *   Packs 4 INT8 pixels per 32-bit write for maximum throughput.
     *   Writes to CNN data SRAM at: (volatile uint32_t *)0x50400000
     *   Total writes: 128*128*3/4 = 12,288 32-bit writes
     */
}

void cnn_start(void)
{
    printf("[CNN_STUB] cnn_start() called. STUB — CNN not actually executing.\r\n");
    /*
     * REAL IMPLEMENTATION:
     *   *((volatile uint32_t *) 0x50100000) = 0x00100808; // CNN_CTRL
     *   *((volatile uint32_t *) 0x50100004) = 0x00000001; // CNN_START
     */
}

void cnn_unload(uint32_t *out_buf)
{
    if (out_buf == NULL) return;

    printf("[CNN_STUB] cnn_unload() called. Returning dummy logits.\r\n");

    /* Stub: return dummy logits simulating a "Matang" (class 1) prediction */
    out_buf[0] = (uint32_t)(-2000);  /* Mentah: low logit (cast from int32) */
    out_buf[1] = (uint32_t)(8000);   /* Matang: highest logit → winner */
    out_buf[2] = (uint32_t)(1000);   /* Overripe: medium logit */
    out_buf[3] = (uint32_t)(-5000);  /* Janjang Kosong: very low logit */
    /*
     * REAL IMPLEMENTATION:
     *   Reads from CNN output SRAM at addresses specific to the synthesized network.
     *   Example: out_buf[i] = *((volatile uint32_t *)(CNN_OUTPUT_BASE + i*4));
     */
}

int cnn_disable(void)
{
    printf("[CNN_STUB] cnn_disable() called.\r\n");
    /*
     * REAL IMPLEMENTATION:
     *   MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);
     *   // Power down CNN SRAM banks
     *   MXC_PWRSEQ->lpcn |= (MXC_F_PWRSEQ_LPCN_RAMRET0 | ...);
     */
    return 0;
}

/* ── MXC_CNN_CheckComplete stub ────────────────────────────────────────────── */
/* In real MSDK: defined in Libraries/PeriphDrivers/Source/CNN/cnn_me17.c */
int MXC_CNN_CheckComplete(void)
{
    /* Stub always returns "done" so the main loop doesn't hang */
    return 1;
}
