/**
 * @file    weights.h
 * @brief   STUB: CNN Weight Arrays Placeholder.
 * @project Edge AI Palm Oil FFB (TBS) Grading System
 *
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║  IMPORTANT: THIS FILE IS A PLACEHOLDER/STUB                        ║
 * ║                                                                      ║
 * ║  Replace this file with the actual weights.h generated by:         ║
 * ║    python ai8xize.py --prefix tbs_cnn --compact-weights ...        ║
 * ║                                                                      ║
 * ║  The real generated file will contain:                              ║
 * ║    - INT8 weight arrays for each CNN layer                          ║
 * ║    - Packed in 32-bit words for memory efficiency                   ║
 * ║    - Total size: ~28 KB (well under 442 KB hardware limit)          ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 */

#ifndef WEIGHTS_H
#define WEIGHTS_H

/* This stub is intentionally empty.
 * The real weights.h will contain large arrays like:
 *
 *   // Layer 0: Conv2d(3→16, 3x3) weights
 *   // 3 * 16 * 3 * 3 = 432 INT8 values packed as 108 uint32_t words
 *   static const uint32_t layer0_weights[] = {
 *       0x01fe02fd, 0x7f812c3a, ...  (432 INT8 values / 4 = 108 words)
 *   };
 *
 *   // ... (similar arrays for all layers)
 *
 * These arrays are referenced by cnn_load_weights() in tbs_cnn.c.
 */

#endif /* WEIGHTS_H */
